# Branch Protection Rules Configuration
# Apply these rules through GitHub UI or API

main:
  required_status_checks:
    strict: true
    contexts:
      - "Lint and Test"
      - "Security Scan"
      - "CodeQL"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
    bypass_pull_request_allowances:
      users: []
      teams: []
      apps: []
  restrictions:
    users: []
    teams: ["core-developers"]
    apps: []
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  lock_branch: false
  allow_fork_syncing: true

staging:
  required_status_checks:
    strict: true
    contexts:
      - "Lint and Test"
      - "Security Scan"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: false
    bypass_pull_request_allowances:
      users: []
      teams: ["developers"]
      apps: []
  restrictions: null
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  lock_branch: false
  allow_fork_syncing: true

development:
  required_status_checks:
    strict: false
    contexts:
      - "Lint and Test"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    require_last_push_approval: false
    bypass_pull_request_allowances:
      users: []
      teams: ["developers"]
      apps: []
  restrictions: null
  allow_force_pushes: true
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: false
  lock_branch: false
  allow_fork_syncing: true
