name: GPT Auto Fix

on:
  workflow_dispatch: {}   # تشغيل يدوي

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set git identity
        run: |
          git config --global user.name "autobot"
          git config --global user.email "autobot@autodropplatform.shop"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install tools
        run: |
          npm i -g openai@1 eslint @eslint/js typescript

      # ✅ فعلّي إصلاحات حقيقية تلقائياً
      - name: ESLint --fix
        run: npx eslint . --ext .ts,.tsx,.js --fix || true

      # ✅ استدعاء OpenAI (تقرير/ملاحظات فقط)
      - name: Ask OpenAI for remaining fixes
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npx openai responses.create \
            -m gpt-4o-mini \
            -i "Review this repo and list the top code issues that still need manual fixes. Prefer TypeScript/Next.js best practices." \
            > openai-report.json || true

      - name: Commit changes (if any)
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: ESLint auto-fix + OpenAI report"
            git push
          else
            echo "No changes to commit."
          fi
